### PR TITLE
Switch hibernate naming strategy

### LINKED ISSUE #11: Hibernate naming strategy
The default naming strategy of hibernate is the [EJB3NamingStrategy](https://docs.jboss.org/hibernate/entitymanager/3.6/reference/en/html/configuration.html#d0e708). The strategy maps camel case attributes like [`userName`](https://github.com/osiam/resource-server/blob/master/src/main/java/org/osiam/storage/entities/UserEntity.java#L47) to the column name `username`. When switching to Spring Boot, the default naming strategy is set by Boot to [ImprovedNamingStrategy](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-jpa-properties). This leads to problems with the column names of camel case entity attributes which are not annotated with `@Column` and a set `name` parameter (e.g. @Column(name = "username") ). I think we should use the [ImprovedNamingStrategy](https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/cfg/ImprovedNamingStrategy.html) before migrate to Spring Boot and add flyway migrations for postgres and mysql to use underscores for mixed case names.

### PR DESCRIPTION
**Pull request by dacrome**
Closes #11
Use ImprovedNamingStrategy instead of the EJB3NamingStrategy

### CODE REVIEW

**Comment by dacrome** [comment]
rebased. who wants to merge?

**Comment by tkrille** [comment]
Great job @dacrome! I'll merge this as soon as https://github.com/osiam/connector4java-integration-tests/pull/246 is ready.

**Comment by tkrille** [comment]
There are still some `@Column`s left that define a `name` attribute, namely:

```
org.osiam.storage.entities.ExtensionFieldEntity#required
org.osiam.storage.entities.BaseMultiValuedAttributeEntity#primary
```

I thought we wanted to get rid of these?

**Comment by dacrome** [comment]
yes. rename columns `is_primary` to `primary` and `is_required` to `required`?

**Comment by wallner** [comment]
@dacrome I think `required`and `primary`are fine. Go for it.

**Comment by dacrome** [comment]
Renamed. But there is problem with the reserved keyword 'primary', dbunit and mysql in the integration-tests. With postgres everything is fine.

**Comment by wallner** [comment]
As already commented on osiam/connector-for-java-integration-tests#246 we should probably keep it as is_required. What do you think?

**Comment by dacrome** [comment]
You mean 'is_primary'. That's why I escaped the primary column name [in the flyway migration script](https://github.com/osiam/resource-server/pull/28/files#diff-0a30adbf96b27da27900c36142fc62f0R5) with backticks, btw the recommanded way to [handle keywords in mysql](https://dev.mysql.com/doc/refman/5.6/en/keywords.html). Everything is fine here, I think dbunit is the problem. So let's switch this discussion to the [integration-test PR](https://github.com/osiam/connector4java-integration-tests/pull/246).

**Comment by tkrille** [comment]
Please revert the rename of `org.osiam.storage.entities.BaseMultiValuedAttributeEntity#primary`. Hibernate doesn't escape it properly when writing data. See also: https://github.com/osiam/connector4java-integration-tests/pull/246#issuecomment-122032637

**Comment by tkrille** [comment]
When do we actually want to move to ES? I heard something about early 2016 :)

**Comment by wallner** [comment]
I think it might need to be earlier than that, considering the trouble we're having. :-)

**Comment by tkrille** [comment]
+1

**Comment by dacrome** [comment]
renamed `primary` back to `is_primary`

**Comment by wallner** [comment]
Looks good! Thank You.

**Pull request merged**
